baseURL = "ctSkennerton.github.io"
languageCode = "en-us"
title = "Connor Skennerton"
theme = "slick"

copyright = "Connor Skennerton — All rights reserved."

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

[params]
# Site subtitle (not shown if commented out or set to false)
    subtitle = "bio(logist | informatician)"

    # Site description
    description = "Connor Skennerton's personal website"

    # Favicon file (relative to baseURL - place below static or assets folder)
    favicon = "favicon.png"
    # Custom css file (relative to baseURL - place below static or assets folder)
    css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateFmt = "02 Jan 2006"

    # Customize the text of the 404 page here
    errorPageText = "There's nothing to see here, please move along!"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = false

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false

# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"

[author]
    name = "Connor Skennerton"
    email = "c.skennerton@gmail.com"


[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0

[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1

    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "About"
        url = "/about/"
        weight = 2
    
    [[menu.main]]
        identifier = "resume"
        name = 'Résumé'
        title = 'Résumé'
        url = "/resume/"
        weight = 3

        # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Theme repository"
        url = "https://github.com/ctSkennerton"
        weight = 1

        [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 1

[permalinks]
  posts = "/:year/:month/:day/:title/"
